name: code_editor
description: "FL IDE — code editor with file tree, QuillCodeEditor and LSP"
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  lsp_client:
    path: ../lsp_client
  dap_client:
    path: ../dap_client
  provider: ^6.1.2
  path: ^1.9.0
  terminal_pkg:
    path: ../terminal_pkg
  ssh_pkg:
    path: ../ssh_pkg

  # Code editor package
  quill_code:
    path: ../../../quill_code

  # Image viewer & file import
  flutter_svg: ^2.0.10
  file_picker: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
